# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\expense_ticket.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_expenseTicket(object):
    def setupUi(self, expenseTicket):
        expenseTicket.setObjectName("expenseTicket")
        expenseTicket.resize(300, 190)
        expenseTicket.setStyleSheet("#expenseTicket\n"
"{\n"
"    background-color: #444444\n"
"}\n"
"\n"
"#lb_coin\n"
"{\n"
"    color: #51FF14;\n"
"    text-align: center;\n"
"    font-family: Inter;\n"
"    fo    nt-size: 15px;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    line-height: normal;\n"
"}\n"
"\n"
"#lb_value\n"
"{\n"
"    color: #FFF;\n"
"    text-align: center;\n"
"    font-family: Inter;\n"
"    font-size: 40px;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    line-height: normal;\n"
"}\n"
"\n"
"#lb_description,\n"
"#lb_description_value,\n"
"#lb_date,\n"
"#lb_date_value\n"
"{\n"
"    color: #FFF;\n"
"    text-align: center;\n"
"    font-family: Inter;\n"
"    font-size: 15px;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    line-height: normal;\n"
"}\n"
"\n"
"\n"
"#btn_edit\n"
"\n"
"{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    outline: none;\n"
"    qproperty-iconSize: 30px 30px;\n"
"    background-position: center;\n"
"}\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(expenseTicket)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lt_expense_value = QtWidgets.QHBoxLayout()
        self.lt_expense_value.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.lt_expense_value.setContentsMargins(0, -1, 0, -1)
        self.lt_expense_value.setSpacing(5)
        self.lt_expense_value.setObjectName("lt_expense_value")
        self.lb_coin = QtWidgets.QLabel(expenseTicket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_coin.sizePolicy().hasHeightForWidth())
        self.lb_coin.setSizePolicy(sizePolicy)
        self.lb_coin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_coin.setObjectName("lb_coin")
        self.lt_expense_value.addWidget(self.lb_coin)
        self.lb_value = QtWidgets.QLabel(expenseTicket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_value.sizePolicy().hasHeightForWidth())
        self.lb_value.setSizePolicy(sizePolicy)
        self.lb_value.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_value.setObjectName("lb_value")
        self.lt_expense_value.addWidget(self.lb_value)
        self.lt_btn_edit = QtWidgets.QVBoxLayout()
        self.lt_btn_edit.setObjectName("lt_btn_edit")
        self.btn_edit = QtWidgets.QPushButton(expenseTicket)
        self.btn_edit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_edit.sizePolicy().hasHeightForWidth())
        self.btn_edit.setSizePolicy(sizePolicy)
        self.btn_edit.setSizeIncrement(QtCore.QSize(0, 0))
        self.btn_edit.setMouseTracking(False)
        self.btn_edit.setTabletTracking(False)
        self.btn_edit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_edit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.btn_edit.setAcceptDrops(False)
        self.btn_edit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_edit.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/expense_ticket/edit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_edit.setIcon(icon)
        self.btn_edit.setIconSize(QtCore.QSize(30, 30))
        self.btn_edit.setCheckable(False)
        self.btn_edit.setObjectName("btn_edit")
        self.lt_btn_edit.addWidget(self.btn_edit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.lt_btn_edit.addItem(spacerItem)
        self.lt_expense_value.addLayout(self.lt_btn_edit)
        self.lt_expense_value.setStretch(0, 1)
        self.lt_expense_value.setStretch(1, 2)
        self.verticalLayout.addLayout(self.lt_expense_value)
        self.lt_description = QtWidgets.QHBoxLayout()
        self.lt_description.setSpacing(10)
        self.lt_description.setObjectName("lt_description")
        self.lb_description = QtWidgets.QLabel(expenseTicket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_description.sizePolicy().hasHeightForWidth())
        self.lb_description.setSizePolicy(sizePolicy)
        self.lb_description.setObjectName("lb_description")
        self.lt_description.addWidget(self.lb_description)
        self.lb_description_value = QtWidgets.QLabel(expenseTicket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_description_value.sizePolicy().hasHeightForWidth())
        self.lb_description_value.setSizePolicy(sizePolicy)
        self.lb_description_value.setObjectName("lb_description_value")
        self.lt_description.addWidget(self.lb_description_value)
        self.lt_description.setStretch(0, 1)
        self.lt_description.setStretch(1, 2)
        self.verticalLayout.addLayout(self.lt_description)
        self.lt_date = QtWidgets.QHBoxLayout()
        self.lt_date.setSpacing(10)
        self.lt_date.setObjectName("lt_date")
        self.lb_date = QtWidgets.QLabel(expenseTicket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_date.sizePolicy().hasHeightForWidth())
        self.lb_date.setSizePolicy(sizePolicy)
        self.lb_date.setObjectName("lb_date")
        self.lt_date.addWidget(self.lb_date)
        self.lb_date_value = QtWidgets.QLabel(expenseTicket)
        self.lb_date_value.setObjectName("lb_date_value")
        self.lt_date.addWidget(self.lb_date_value)
        self.lt_date.setStretch(0, 1)
        self.lt_date.setStretch(1, 2)
        self.verticalLayout.addLayout(self.lt_date)

        self.retranslateUi(expenseTicket)
        QtCore.QMetaObject.connectSlotsByName(expenseTicket)

    def retranslateUi(self, expenseTicket):
        _translate = QtCore.QCoreApplication.translate
        expenseTicket.setWindowTitle(_translate("expenseTicket", "Form"))
        self.lb_coin.setText(_translate("expenseTicket", "R$"))
        self.lb_value.setText(_translate("expenseTicket", "250,00"))
        self.lb_description.setText(_translate("expenseTicket", "Descrição:"))
        self.lb_description_value.setText(_translate("expenseTicket", "Placa de vídeo GT..."))
        self.lb_date.setText(_translate("expenseTicket", "Data: "))
        self.lb_date_value.setText(_translate("expenseTicket", "24/08/2023"))
import resource_rc
