# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'limit_and_expense.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_limitAndExpense(object):
    def setupUi(self, limitAndExpense):
        limitAndExpense.setObjectName("limitAndExpense")
        limitAndExpense.resize(288, 52)
        limitAndExpense.setStyleSheet("#limitAndExpense\n"
"{\n"
"    background-color: #232327;\n"
"}\n"
"\n"
"#lb_expense, #lb_limit\n"
"{\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"}\n"
"\n"
"#lb_value_expense , #lb_value_limit\n"
"{\n"
"    color: #77AE7D;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"}\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(limitAndExpense)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lb_expense = QtWidgets.QLabel(limitAndExpense)
        self.lb_expense.setObjectName("lb_expense")
        self.verticalLayout.addWidget(self.lb_expense)
        self.lb_value_expense = QtWidgets.QLabel(limitAndExpense)
        self.lb_value_expense.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_value_expense.setObjectName("lb_value_expense")
        self.verticalLayout.addWidget(self.lb_value_expense)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lb_limit = QtWidgets.QLabel(limitAndExpense)
        self.lb_limit.setObjectName("lb_limit")
        self.verticalLayout_2.addWidget(self.lb_limit)
        self.lb_value_limit = QtWidgets.QLabel(limitAndExpense)
        self.lb_value_limit.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_value_limit.setObjectName("lb_value_limit")
        self.verticalLayout_2.addWidget(self.lb_value_limit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)

        self.retranslateUi(limitAndExpense)
        QtCore.QMetaObject.connectSlotsByName(limitAndExpense)

    def retranslateUi(self, limitAndExpense):
        _translate = QtCore.QCoreApplication.translate
        limitAndExpense.setWindowTitle(_translate("limitAndExpense", "Form"))
        self.lb_expense.setText(_translate("limitAndExpense", "GASTO DO MÊS"))
        self.lb_value_expense.setText(_translate("limitAndExpense", "0"))
        self.lb_limit.setText(_translate("limitAndExpense", "LIMITE"))
        self.lb_value_limit.setText(_translate("limitAndExpense", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    limitAndExpense = QtWidgets.QWidget()
    ui = Ui_limitAndExpense()
    ui.setupUi(limitAndExpense)
    limitAndExpense.show()
    sys.exit(app.exec_())
